# Site settings
author: Jordan Romero
title: Part Time Immersive 3/02 Cohort
header-img: img/home-bg.png
email: jordan.t.romero@gmail.com
copyright_name: Jordan Romero
description: > # this means to ignore newlines until "baseurl:"
  Learning objectives 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jordles113

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
